export const data = [
    {
      question: "Which type of bond involves the sharing of electron pairs between atoms?",
      option1: "Ionic Bond",
      option2: "Covalent Bond",
      option3: "Metallic Bond",
      option4: "Hydrogen Bond",
      ans: 2,
    },
    {
      question: "What type of bond is formed when one atom transfers an electron to another atom?",
      option1: "Ionic Bond",
      option2: "Covalent Bond",
      option3: "Metallic Bond",
      option4: "Polar Bond",
      ans: 1,
    },
    {
      question: "In which type of bond do positively charged metal ions attract a 'sea' of delocalized electrons?",
      option1: "Covalent Bond",
      option2: "Ionic Bond",
      option3: "Metallic Bond",
      option4: "Hydrogen Bond",
      ans: 3,
    },
    {
      question: "Which of the following molecules contains a polar covalent bond?",
      option1: "O₂",
      option2: "H₂O",
      option3: "CH₄",
      option4: "N₂",
      ans: 2,
    },
    {
      question: "What is the main characteristic of ionic compounds?",
      option1: "They are formed by sharing electrons.",
      option2: "They have high melting and boiling points.",
      option3: "They conduct electricity in solid form.",
      option4: "They are usually gases at room temperature.",
      ans: 2,
    },
    {
      question: "Which of the following statements about metallic bonding is true?",
      option1: "It involves the transfer of electrons.",
      option2: "It involves the sharing of electrons.",
      option3: "It involves a lattice of positive ions in a 'sea' of electrons.",
      option4: "It only occurs in transition metals.",
      ans: 3,
    },
    {
      question: "Which type of bond is typically the strongest?",
      option1: "Ionic Bond",
      option2: "Covalent Bond",
      option3: "Hydrogen Bond",
      option4: "Metallic Bond",
      ans: 2,
    },
    {
      question: "Which of the following compounds is an example of an ionic compound?",
      option1: "NaCl",
      option2: "CO₂",
      option3: "CH₄",
      option4: "H₂O",
      ans: 1,
    },
    {
      question: "What determines the polarity of a molecule?",
      option1: "The number of atoms in the molecule.",
      option2: "The electronegativity difference between atoms.",
      option3: "The molecular weight of the compound.",
      option4: "The size of the atoms involved.",
      ans: 2,
    },
    {
      question: "Which of the following describes a nonpolar covalent bond?",
      option1: "Electrons are transferred from one atom to another.",
      option2: "Electrons are shared equally between atoms.",
      option3: "Electrons are shared unequally between atoms.",
      option4: "It involves only hydrogen atoms.",
      ans: 2,
    },
    {
      question: "Which of the following compounds contains a double bond?",
      option1: "CH₄",
      option2: "CO₂",
      option3: "NH₃",
      option4: "H₂",
      ans: 2,
    },
    {
      question: "What is the geometry of a molecule with two bonding pairs and no lone pairs on the central atom?",
      option1: "Linear",
      option2: "Bent",
      option3: "Trigonal Planar",
      option4: "Tetrahedral",
      ans: 1,
    },
    {
      question: "Which of the following is a characteristic of ionic compounds?",
      option1: "They are usually soft and malleable.",
      option2: "They have low melting points.",
      option3: "They conduct electricity when dissolved in water.",
      option4: "They are gases at room temperature.",
      ans: 3,
    },
    {
      question: "Which type of bonding is primarily responsible for the properties of metals?",
      option1: "Ionic Bonding",
      option2: "Covalent Bonding",
      option3: "Metallic Bonding",
      option4: "Hydrogen Bonding",
      ans: 3,
    },
    {
      question: "Which of the following statements is true about hydrogen bonds?",
      option1: "They are stronger than covalent bonds.",
      option2: "They are a type of ionic bond.",
      option3: "They occur between molecules with hydrogen bonded to highly electronegative atoms.",
      option4: "They only occur in organic compounds.",
      ans: 3,
    },
  ];
  

// export const data = [
//   {
//     question: "What type of bond involves the sharing of electron pairs between atoms?",
//     option1: "Ionic Bond",
//     option2: "Covalent Bond",
//     option3: "Metallic Bond",
//     option4: "Hydrogen Bond",
//     ans: 2,
//   },
//   {
//     question: "Which of the following pairs of elements would likely form an ionic bond?",
//     option1: "Carbon and Oxygen",
//     option2: "Sodium and Chlorine",
//     option3: "Hydrogen and Helium",
//     option4: "Nitrogen and Fluorine",
//     ans: 2,
//   },
//   {
//     question: "What is the main characteristic of metallic bonding?",
//     option1: "Sharing of electrons",
//     option2: "Transfer of electrons",
//     option3: "Sea of delocalized electrons",
//     option4: "Hydrogen bonding",
//     ans: 3,
//   },
//   {
//     question: "Which type of bond is the strongest?",
//     option1: "Ionic Bond",
//     option2: "Covalent Bond",
//     option3: "Hydrogen Bond",
//     option4: "Van der Waals Forces",
//     ans: 2,
//   },
//   {
//     question: "What determines the type of bond formed between two atoms?",
//     option1: "Their mass",
//     option2: "Their electronegativity",
//     option3: "Their temperature",
//     option4: "Their state of matter",
//     ans: 2,
//   },
//   {
//     question: "Which of the following molecules has a polar covalent bond?",
//     option1: "O2",
//     option2: "H2O",
//     option3: "CH4",
//     option4: "N2",
//     ans: 2,
//   },
//   {
//     question: "Which element is most likely to form a cation?",
//     option1: "Chlorine",
//     option2: "Oxygen",
//     option3: "Sodium",
//     option4: "Nitrogen",
//     ans: 3,
//   },
//   {
//     question:
//       "What is the shape of a molecule with two bonding pairs and no lone pairs?",
//     option1: "Linear",
//     option2: "Bent",
//     option3: "Tetrahedral",
//     option4: "Trigonal planar",
//     ans: 1,
//   },
//   {
//     question: "Which of the following compounds contains an ionic bond?",
//     option1: "CO2",
//     option2: "MgO",
//     option3: "NH3",
//     option4: "CCl4",
//     ans: 2,
//   },
//   {
//     question: "What type of bond holds the atoms in a metal together?",
//     option1: "Covalent Bond",
//     option2: "Ionic Bond",
//     option3: "Metallic Bond",
//     option4: "Polar Bond",
//     ans: 3,
//   },
//   {
//     question:
//       "Which of the following properties is typical of ionic compounds?",
//     option1: "They are good conductors of electricity in solid state.",
//     option2: "They have low melting and boiling points.",
//     option3: "They are soluble in water.",
//     option4: "They are malleable and ductile.",
//     ans: 3,
//   },
//   {
//     question:
//       "What type of hybridization occurs in a molecule with four bonding pairs?",
//     option1: "sp",
//     option2: "sp2",
//     option3: "sp3",
//     option4: "dsp3",
//     ans: 3,
//   },
//   {
//     question: "Which of the following statements about hydrogen bonds is true?",
//     option1: "They are stronger than covalent bonds.",
//     option2: "They occur between hydrogen and electronegative atoms.",
//     option3: "They can only occur in water.",
//     option4: "They are permanent.",
//     ans: 2,
//   },
//   {
//     question:
//       "What is the bond angle in a molecule with a trigonal planar shape?",
//     option1: "90°",
//     option2: "120°",
//     option3: "180°",
//     option4: "109.5°",
//     ans: 2,
//   },
//   {
//     question: "Which of the following best describes a nonpolar covalent bond?",
//     option1: "A bond between atoms with similar electronegativities.",
//     option2: "A bond formed between a metal and a nonmetal.",
//     option3: "A bond that involves the transfer of electrons.",
//     option4: "A bond that results in the formation of ions.",
//     ans: 1,
//   },
// ];
