export const data = [
  {
    question: "What type of bond involves the sharing of electron pairs between atoms?",
    option1: "Ionic Bond",
    option2: "Covalent Bond",
    option3: "Metallic Bond",
    option4: "Hydrogen Bond",
    ans: 2,
  },
  {
    question: "Which of the following pairs of elements would likely form an ionic bond?",
    option1: "Carbon and Oxygen",
    option2: "Sodium and Chlorine",
    option3: "Hydrogen and Helium",
    option4: "Nitrogen and Fluorine",
    ans: 2,
  },
  {
    question: "What is the main characteristic of metallic bonding?",
    option1: "Sharing of electrons",
    option2: "Transfer of electrons",
    option3: "Sea of delocalized electrons",
    option4: "Hydrogen bonding",
    ans: 3,
  },
  {
    question: "Which type of bond is the strongest?",
    option1: "Ionic Bond",
    option2: "Covalent Bond",
    option3: "Hydrogen Bond",
    option4: "Van der Waals Forces",
    ans: 2,
  },
  {
    question: "What determines the type of bond formed between two atoms?",
    option1: "Their mass",
    option2: "Their electronegativity",
    option3: "Their temperature",
    option4: "Their state of matter",
    ans: 2,
  },
  {
    question: "Which of the following molecules has a polar covalent bond?",
    option1: "O2",
    option2: "H2O",
    option3: "CH4",
    option4: "N2",
    ans: 2,
  },
  {
    question: "Which element is most likely to form a cation?",
    option1: "Chlorine",
    option2: "Oxygen",
    option3: "Sodium",
    option4: "Nitrogen",
    ans: 3,
  },
  {
    question:
      "What is the shape of a molecule with two bonding pairs and no lone pairs?",
    option1: "Linear",
    option2: "Bent",
    option3: "Tetrahedral",
    option4: "Trigonal planar",
    ans: 1,
  },
  {
    question: "Which of the following compounds contains an ionic bond?",
    option1: "CO2",
    option2: "MgO",
    option3: "NH3",
    option4: "CCl4",
    ans: 2,
  },
  {
    question: "What type of bond holds the atoms in a metal together?",
    option1: "Covalent Bond",
    option2: "Ionic Bond",
    option3: "Metallic Bond",
    option4: "Polar Bond",
    ans: 3,
  },
  {
    question:
      "Which of the following properties is typical of ionic compounds?",
    option1: "They are good conductors of electricity in solid state.",
    option2: "They have low melting and boiling points.",
    option3: "They are soluble in water.",
    option4: "They are malleable and ductile.",
    ans: 3,
  },
  {
    question:
      "What type of hybridization occurs in a molecule with four bonding pairs?",
    option1: "sp",
    option2: "sp2",
    option3: "sp3",
    option4: "dsp3",
    ans: 3,
  },
  {
    question: "Which of the following statements about hydrogen bonds is true?",
    option1: "They are stronger than covalent bonds.",
    option2: "They occur between hydrogen and electronegative atoms.",
    option3: "They can only occur in water.",
    option4: "They are permanent.",
    ans: 2,
  },
  {
    question:
      "What is the bond angle in a molecule with a trigonal planar shape?",
    option1: "90°",
    option2: "120°",
    option3: "180°",
    option4: "109.5°",
    ans: 2,
  },
  {
    question: "Which of the following best describes a nonpolar covalent bond?",
    option1: "A bond between atoms with similar electronegativities.",
    option2: "A bond formed between a metal and a nonmetal.",
    option3: "A bond that involves the transfer of electrons.",
    option4: "A bond that results in the formation of ions.",
    ans: 1,
  },
];
